import { requestJson } from './requestDeadline.mjs';

export async function submitTradeApplication({
  email,
  username,
  password,
  confirmPassword,
  contactName,
  businessName,
  phone,
  companyAddress,
  deliveryAddress,
  streetName,
  suburb,
  postalCode,
  buildingType,
  unitNumber,
  vatNumber,
  country,
  province,
  city,
  businessType,
  salesChannels,
  productCategories,
  otherProductCategory,
  businessDescription,
  monthlySpend,
  website,
  acceptWhatsapp,
  customerCode,
  company_fax,
}) {
  return requestJson('/api/register-trade', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email,
      username,
      password,
      confirmPassword,
      contactName,
      businessName,
      phone,
      companyAddress,
      deliveryAddress,
      streetName,
      suburb,
      postalCode,
      buildingType,
      unitNumber,
      vatNumber,
      country,
      province,
      city,
      businessType,
      salesChannels,
      productCategories,
      otherProductCategory,
      businessDescription,
      monthlySpend,
      website,
      acceptWhatsapp,
      customerCode,
      company_fax,
    }),
  }, {
    timeoutMs: 25_000,
    message: 'We could not confirm your application. Check your email for confirmation before trying again. Your form is still here.',
  });
}
