import assert from 'node:assert/strict';
import test from 'node:test';
import { createApolloActivityHandler } from '../api/apollo-activity.js';
const user={id:'a9894746-a04f-4d6d-82b3-4a3819354565'}; const body={event_id:'b9894746-a04f-4d6d-82b3-4a3819354565',session_id:user.id,source:'main',event_type:'category_view',occurred_at:'2026-09-12T10:00:00Z',category:{id:'home'}};
function run(options={}, input=body){const calls=[];const sb={calls,from(){return{insert:async(row,opts)=>{calls.push({row,opts});return options.db||{error:null};}};}};let status=0,payload;const res={setHeader(){},status(c){status=c;return this;},json(p){payload=p;return this;}};const handler=createApolloActivityHandler({source:'main',enabled:()=>options.enabled!==false,verify:async()=>options.user===undefined?user:options.user,client:()=>sb,now:()=>Date.parse('2026-09-12T10:01:00Z')});return handler({method:options.method||'POST',body:input},res).then(()=>({status,payload,calls}));}
test('disabled is fail closed',async()=>assert.equal((await run({enabled:false})).status,404));
test('inserts trusted identity idempotently and returns no private data',async()=>{const r=await run();assert.equal(r.status,202);assert.equal(r.calls[0].row.customer_id,user.id);assert.deepEqual(r.calls[0].opts,{onConflict:'event_id',ignoreDuplicates:true});assert.deepEqual(r.payload,{ok:true});});
test('rejects anonymous, foreign identity and oversized events',async()=>{assert.equal((await run({user:null})).status,401);assert.equal((await run({}, {...body,customer_id:user.id})).status,400);assert.equal((await run({}, {...body,payload:{text:'x'.repeat(20000)}})).status,413);});
test('POST only and generic insert failure',async()=>{assert.equal((await run({method:'GET'})).status,405);assert.equal((await run({db:{error:{message:'private'}}})).status,503);});
test('rejects source mismatch before client use',async()=>{let called=false;await createApolloActivityHandler({source:'instore',enabled:()=>true,verify:async()=>user,client:()=>{called=true;return{};}})({method:'POST',body}, {setHeader(){},status(c){this.code=c;return this;},json(){return this;}});assert.equal(called,false);});
test('rejects nested extras and cross-type payloads',async()=>{assert.equal((await run({}, {...body,category:{id:'x',extra:{customer:user.id}}})).status,400);assert.equal((await run({}, {...body,product:{id:'x'}})).status,400);});
test('does not create default client when invalid',async()=>{const handler=createApolloActivityHandler({enabled:()=>true,source:'main',verify:async()=>user});const res={status(c){this.code=c;return this;},json(){return this;},setHeader(){}};await handler({method:'POST',body:{bad:true}},res);assert.equal(res.code,400);});
test('does not echo private database errors',async()=>{const r=await run({db:{error:{message:'secret customer data'}}});assert.deepEqual(r.payload,{error:'Activity could not be recorded'});});
test('rejects events outside the one-day database intake window before database use',async()=>{const r=await run({}, {...body,occurred_at:'2026-09-11T10:00:59Z'});assert.equal(r.status,400);assert.equal(r.calls.length,0);});
