-- 027_move_4_fashion_accessories.sql  (STOCK Supabase project)
-- Recategorise 1,114 SKUs from Move 4.xlsx into the Fashion & Accessories taxonomy.
-- 29 boutique paper bags -> Packaging & Storage > ... > Paper Bags > Boutique.
-- Source workbook: scripts/data/Move_4_fashion_accessories.xlsx

begin;

create temp table move_4_targets (
  sku text primary key,
  category text not null,
  subcategory_one text not null,
  subcategory_two text,
  subcategory_three text,
  subcategory_four text
) on commit drop;

insert into move_4_targets (sku, category, subcategory_one, subcategory_two, subcategory_three, subcategory_four) values
  ('0001-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0001-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0001-SKBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0001-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0002-COR', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0002-SKBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0002-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0004-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0004-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0004-PNK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0025-BGY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0025-NAV', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0026-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0026-EMGRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0026-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0026-REDS', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0044-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0044-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0044-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0047-CRM', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0047-DKGRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0047-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0047-LTBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0048-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0048-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0048-OFWHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0051-BLK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0051-CRM', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0051-PNK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0054-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0054-CRM', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0054-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0054-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0057-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0057-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0058-BEI', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0058-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0058-OFWHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('7134-BEI', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('7134-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('7134-CAM', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('7134-CRM', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('7134-GRY', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('7134-WHT', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('7210-BEI', 'Fashion & Accessories', 'Hats & Caps', 'Panama', null, null),
  ('7210-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Panama', null, null),
  ('7210-BRN', 'Fashion & Accessories', 'Hats & Caps', 'Panama', null, null),
  ('7210-CAM', 'Fashion & Accessories', 'Hats & Caps', 'Panama', null, null),
  ('7210-CRM', 'Fashion & Accessories', 'Hats & Caps', 'Panama', null, null),
  ('7210-GRY', 'Fashion & Accessories', 'Hats & Caps', 'Panama', null, null),
  ('8778-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('8788-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('8788-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9124-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9124-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9124-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9124-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9157-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9320-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9320-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9338-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9491-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9545-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9545-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9545-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9554-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9607-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9608-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9608-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9620-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9620-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9620-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9626-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9701-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9701-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9701-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9701-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9703-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9703-NAT2', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9737-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9737-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9739-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9739-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9756-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9761-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9766-BLK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9766-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9766-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9769-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9769-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('9769-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ATM0151P-E13', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('ATM0151P-E14', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('ATM0151P-F210', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('ATM0151P-F212', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('ATM0151P-F215', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('ATM0151P-F216', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('ATM0151P-F217', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('ATMBB-A1', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('ATMBB-A2', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('ATMBB-A3', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('ATMBB-A4', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('ATMBB-A5', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('ATMBB-A6', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('ATMBB-A7', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('ELS1-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ELS1-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ELS1-NAV', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ELS1-OFWHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ELS58-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ELS58-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ELS58-NAV', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('ELS58-OFWHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0018-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0018-OFWHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0018-TEL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('79002-PNK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('79002-YEL', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('97031-PNK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('30002-BEI', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('30002-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('77033-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('77035-PNK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('77276-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('48005-GLD', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('48005-RED', 'Fashion & Accessories', 'Hats & Caps', 'Fedora', null, null),
  ('62001-PUR', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('62001-RED', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('62001-WHT', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('80001-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('68001-MUL', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('62005-GLD', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('62005-SIL', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('44004-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('53006-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('97020-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('64001-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('97027-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('42102-NAT', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('101-2-T', 'Fashion & Accessories', 'Synthetic Bags', 'Luggage & Laptop', null, null),
  ('101-2-GP', 'Fashion & Accessories', 'Synthetic Bags', 'Luggage & Laptop', null, null),
  ('PENBAG-M30', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('0224-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0224-TUR', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0224-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0224-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0234-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0234-NBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0234-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0236-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0236-KHA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0236-LTBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0236-PEA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0236-RBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0236-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0237-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0237-KHA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0237-LTBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0237-PEA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0237-RBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0237-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0235-GRE', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0235-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0235-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0235-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0235-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0233-CER', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0233-ORA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0233-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0230-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0230-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0230-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0230-CRE', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0231-CER', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0231-RDBRO', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0231-ORA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0221-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0221-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0221-DPIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0222-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0222-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0231-BLUE', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0222-PEA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-BLK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-DKGRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-LTBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-MTGRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-PEA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0229-NBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0229-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0229-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0211-BEI', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0228-LTGRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0228-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0228-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0228-BEI', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0228-CRE', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0228-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0041-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0041-DKGRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0041-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0041-DKBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0041-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0229-LTGRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0041-LTBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0219-LTBEI', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0219-LTSTN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0009-LTBRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0009-MRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0009-NBLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0009-TEA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0220-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0220-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0220-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0239-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0239-PEA', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0239-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0238-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0238-PIN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('JDSF4A-BW', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('COSPROL-DBB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COSPROL-GB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COSPROL-GW', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COSPROL-RB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COSPROL-GC', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COSPROL-YB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COSPROL-OB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PENPRO-DBB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PENPRO-GB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PENPRO-GW', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PENPRO-RB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PENPRO-GC', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PENPRO-YB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PENPRO-OB', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('7275-RED', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('7275-RBLU', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('7273-FAWN', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('7273-GRY', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('BB0068-NAT', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('BB0069-NAT', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('BB0070-NAT', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('BB0075-BLK', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('BB0073-SIL', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('COS10-BGBK', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS10-BGRD', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS12-GRBG', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS12-GRBL', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS12-GRCM', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS12-GRRD', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PCAS4-BGBK', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PCAS4-BGRD', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PCAS5-GRBG', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PCAS5-GRBL', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PCAS5-GRCM', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PCAS5-GRRD', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PCAS5-GRGN', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('0416-PHRD', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0416-CMBL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0416-WTBL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0416-WTPK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0415-PKTL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0415-PKGR', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0415-GRPK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0415-MNBN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0408-PKCL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0408-WTCL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0408-WTGY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0411-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0411-NAT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0411-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0412-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0412-YEL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0409-YWBL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0409-CLTQ', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0409-PKGY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0409-BKGY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0413-BLRD', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0413-GNYW', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0413-OGBL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0413-TQMN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0414-BLOG', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0414-GNPK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0414-GYYW', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0414-OGBL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0410-BLSTP', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0410-WTSTP', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0407-BLGY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0407-NVMN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0406-BNBG', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0406-GNGY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0406-MDCM', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0406-PKBG', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('0406-PKGY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('JDS8-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('JDS7-SIL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('STB01-BP-A', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('STB01-BP-B', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('STB01-BP-C', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('431-GR-GD', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('432-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('433-BGE', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('434-BGE', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('434-BRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('434-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('436-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('436-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('436-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('436-PNK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('436-YEL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('437-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('437-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('437-BLK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('441-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('441-CRL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('441-BRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('441-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('439-BLK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('439-PNK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('439-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('439-YEL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('440-PNK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('440-TUR', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('440-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('438-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('438-GRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('442-PNK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('442-YEL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('443-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('443-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('443-GRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('437-BLU', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('441-PNK', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('441-TEL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('438-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('442-RED', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('442-DNM', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('443-CRL', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('WAL-075', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-077', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-078', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('MWAL-114', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('MWAL-113', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('MWAL-115', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('BS0052-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0052-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0051-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0051-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0049-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0049-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0048-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0047-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0044-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-I', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-H', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-G', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-F', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-E', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-D', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-C', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0042-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0039-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0038-D', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0038-C', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0038-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0038-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0034-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0034-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-I', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-H', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-G', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-F', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-E', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-D', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-C', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0025-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0024-F', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0024-E', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0024-D', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0024-C', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0024-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0024-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0020-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0020-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0018-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0017-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0010-D', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0010-C', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0010-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0010-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0007-E', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0007-D', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0007-C', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0007-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0007-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0001-E', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0001-D', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0001-C', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0001-B', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('BS0001-A', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('SCF-509', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('SCF-506', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('SCF-505', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('SCF-498', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('SCF-492', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('SCF-485', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('COS-0032', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0028', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0026', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0033', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0025', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0024', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0118', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0090', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0089', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0087', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0159', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0158', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('0026-BLUGRN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0026-REDBLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0026-RED', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0001-CRM', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0001-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0001-TAN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0010-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0010-LBRN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0010-BRN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0010-CRM', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('870027-BEI', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('870027-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0020-TOF', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0020-LPNK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0020-PNK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0020-CRM', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0020-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0009-WHT', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0009-PNK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0009-BEI', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0009-LBEI', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0009-GRY', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0009-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0026-REDWHT', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('860009-BEI', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('860009-BRN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('860009-GRY', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('860009-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('860010-RED', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('860010-BRN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('860010-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0011-RED', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0011-LTAU', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0011-GRN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0011-PNK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0011-TAN', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0011-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0007-LGRY', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0007-BEI', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0007-BLU', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0007-CRM', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0007-BLK', 'Fashion & Accessories', 'Leather', 'Bag Straps', null, null),
  ('0024-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0024-LBRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0024-CRM', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0024-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0005-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0005-CRM', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0026-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('0026-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('0026-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('0035-MULBRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('242-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0033-STNGRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0033-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0032-TAN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0032-BLKA', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-TAN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-CRM', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0030-NBLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0030-CRM', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0030-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0025-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0025-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0019-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0019-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0019-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-STN-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-STN-BRH', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-STN-BLH', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0024-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860024-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860027-DPNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860027-DMAU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860027-CRM', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860027-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0028-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0028-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0028-SAL', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0028-NAT', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0031-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0031-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0031-DBLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0031-TAU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0031-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0021-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0021-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0020-ORG', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0020-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0020-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0019-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0019-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0019-CRM', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0018-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0018-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0018-LBEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0018-DBRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0016-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0016-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0016-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0016-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0016-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0014-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0014-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0014-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0008-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0008-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0008-LBRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0008-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0008-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0005-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0005-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860005-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860005-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860005-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860005-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860005-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860017-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860017-YEL', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860017-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860017-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860013-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860013-TAU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860013-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860015-TAN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860015-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860015-BEIB', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860015-BEIA', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860023-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860023-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860023-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860022-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860022-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860022-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860022-TAU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860022-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860012-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860012-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860012-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860012-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870002-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860001-ORG', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860001-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860001-TAU', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860001-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860002-SDL', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860002-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860002-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860002-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('860002-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('870012-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870012-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870012-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870004-DORG', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870004-YEL', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870004-LBLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870004-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870004-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870004-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0001-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0033-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870002-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Backpack & Shoulder', null, null),
  ('870014-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870014-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870028-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870028-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870028-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870028-WHT', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870028-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0025-DPNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0025-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0025-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860010-WHT', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860006-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860006-NAV', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860006-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860006-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870013-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870013-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870013-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870015-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870025-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870022-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870022-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870022-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870022-ORG', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870022-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870022-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870022-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0032-DBRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860007-YEL', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860007-MAR', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860007-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860007-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860004-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860004-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860004-DBRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860004-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860004-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860003-GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860003-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860003-RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860003-WHT', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860003-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860003-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('0029-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870021-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870021-BEI', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870021-GRY', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870021-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870016-PUR', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870016-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870016-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('870012-BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('860006-BRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('COS-0003RED', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0003BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0003WHT', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0003PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0003GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('CBV870007-GRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CBP870007-GRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CBP870007-BEI', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CBS870007-GRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CBS870007-BLU', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CBS870007-BEI', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CBS870007-BRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CBS870007-BLK', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CB870007-ORG', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CB870007-BLU', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CB870007-BEI', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CB870007-BRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CB870007-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('BEA0004-PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BEA0004-BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('8616500080.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500081.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('F103971604', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500237.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500236.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500012.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500017.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500082.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500245.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500085.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500235.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500016.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('TAR202253', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500084.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('F103971602', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500244.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500005B', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500005A', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500083.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('F103971601', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500014.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500257.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('H487', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('8616500256.0', 'Packaging & Storage', 'Packaging Packets and Bags', 'Paper Bags', 'Boutique', null),
  ('GY18-BEI', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('GY18-CAM', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('GY18-WHT', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('GY18-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('GY80-BEI', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('GY80-CAM', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('GY80-WHT', 'Fashion & Accessories', 'Hats & Caps', 'Sunhats', null, null),
  ('004002-AST', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('004002-RED', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('004002-YEL', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('004002-GRN', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('004002-NBLU', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('004002-RBLU', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('004002-WHT', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('004002-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-AST', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-RED', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-YEL', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-GRN', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-NBLU', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-RBLU', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-WHT', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('020002-BLK', 'Fashion & Accessories', 'Hats & Caps', 'Hair Accessories', null, null),
  ('8611600074.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600169.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600080.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600081.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600078.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600077.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600088.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600157B', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600157A', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600008.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600095.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600087.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600015.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600090.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600086.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600010.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600124.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600093.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600085.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600292.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600293.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600183.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600294.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600243.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600173.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600009.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600076.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600251.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600255.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600053.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600121.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600153.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600240.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600241.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600159.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600059.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600266.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600151.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600150.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600277.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600237.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600236.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600212.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600213.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600180.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600211.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600179.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600300.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600014.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600299.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600283.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8911600156.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600290.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600278.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600205.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600162.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600181.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600176.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600065.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600167.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600064.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600177.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600170.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600279.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600208.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600280.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600235.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600066.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600291.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('8611600232.0', 'Fashion & Accessories', 'Iron-On Patch', null, null, null),
  ('PUR-0174B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0174A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0011B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0011A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0009E', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0009D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0009C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0009B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0009A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0002', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0180', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0182', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0183', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0184', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0185', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0186', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0188', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0189', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0190', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0191', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0192', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0187', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0181', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0193', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0194', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0195', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0202', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0201', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0203', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0204', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0171E', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0171D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0171C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0171B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0171A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0169C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0169B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0169A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0090', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0091', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0092', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0197', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0196', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0199', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('WAL-0200', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PEN-0094', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0096', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0097', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0098', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0099', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0095', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0093', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0100', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PEN-0101', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0052E', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0052D', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0052C', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0052B', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0052A', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0074', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0076', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0077', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0078', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0079', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0080', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0082', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0083', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0084', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0085', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0081', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0075', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0087.2', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0088', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('PUR-0089.2', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0028.2', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0062', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0061', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0063', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0064', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0048', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0057', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0058', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0059', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('COS-0060', 'Fashion & Accessories', 'Synthetic Bags', 'Small Accessories', null, null),
  ('TOT-0054', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0052', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0055', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0051', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0050', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0056', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0057', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0053', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0070', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0072', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0071', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('TOT-0073', 'Fashion & Accessories', 'Synthetic Bags', 'Tote', null, null),
  ('PUR-0174D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('PUR-0174C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('0013BLUC', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013CRMC', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013-CAMC', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013PINKB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013BLUB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013CRMB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013NATB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013CAMB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013PNKA', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013CRMA', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013NATA', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('0013CAMA', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('BW-0013PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('BW-0013BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('BW-0013NAT', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('BW-0013CAM', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-0019PUR', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-0019DPNK', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-0019WHT', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-0019LPNK', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-007LPNKB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-007BLUB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-007DPNKB', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-007BLUA', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-007LPNKA', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('S-007DPNKA', 'Fashion & Accessories', 'Synthetic Bags', 'Sling & Crossbody', null, null),
  ('BB-002YEL', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-002RED', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-002PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-002BLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-002BLK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-005PUR', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-005PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-005GRN', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-005NBLB', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('BB-005NBLA', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('MB-003PUR', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('MB-003PNK', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('MB-003YEL', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('MB-003MNT', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('MB-003NBLU', 'Fashion & Accessories', 'Synthetic Bags', 'Handbags', null, null),
  ('CPUR-0036F', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0036E', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0036D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0036C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0036B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0036A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0069', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0068', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0067', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0066', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0065', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0064', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0063', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0062', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0061', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0060', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0059', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0058', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0179F', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0179E', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0179D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0179C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0179B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0179A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0178C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0178B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0178A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0177E', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0177D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0177C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0177B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0177A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0167E', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0167D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0167C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0167B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0167A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('CPUR-0178A-1', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAG97-GRY', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG97-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG96-MGRY', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG96-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TRH1-MAR', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENPB-F', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('SENPB-E', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('SENPB-D', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('SENPB-C', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('SENPB-B', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('SENPB-A', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('CHE11-RBRN', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('CHE11-BLK', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('LS15B-BEI', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS15B-BLK', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS15B-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS15B-BRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TRS10-EGRN', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('TRS10-BEI', 'Fashion & Accessories', 'Leather', 'Small Accessories', null, null),
  ('TBAGP-MGRY', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGP-BLK', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGP-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENHP-F', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENHP-E', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENHP-D', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENHP-C', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENHP-B', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENHP-A', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAG75-MGRY', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG75-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG58-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENP-HPC', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENP-HPB', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENP-HPA', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('SENPA-LG-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW1-BLK', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW1-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS27-BLK', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS27-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS27-BRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS17C-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS17-GRY', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS17-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('LS17-DBRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAW2-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAW2-BLK', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-GRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-RBRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-GRY', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-MGRY', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-BLK', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-BRN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-MTAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TBAGW-TAN', 'Fashion & Accessories', 'Leather', 'Wallets & Purses', null, null),
  ('TRS4-EGRN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TRS4-TAN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TBAGLT-RBRN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TBAGLT-BRN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TBAGLT-TAN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TBAG33-TAN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TBAG12-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG91-DBRN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TBAG91-TAN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TLUG2-TAN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TLUG1-REDBRN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TLUG1-DBRN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TLUG1-TAN', 'Fashion & Accessories', 'Leather', 'Luggage & Laptop', null, null),
  ('TBAG27-BRN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG27-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG38C-BLK', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG38B-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG38A-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAGB-DBRN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAGB-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG92-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG55-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG95S-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG95M-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TBAG95L-TAN', 'Fashion & Accessories', 'Leather', 'Backpack & Shoulder', null, null),
  ('TRS9-DBEI', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TRS9-LBEI', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TRS9-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENSLIM-GRN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENSLIM-RED', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENSLIM-BLK', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENSLIM-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENBB-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENLB-LBRN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENLB-DBRN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENHP1-F', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENHP1-E', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENHP1-D', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENHP1-C', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENHP1-B', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENHP1-A', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('SENP-L-DTAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('SENP-L-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG39-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG7-RBRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG7B-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('MARK2-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG50-MGRY', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG50-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG37-MGRY', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG37-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG7A-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG2-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('CHE7-3Z-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('CHE7-3Z-MLBRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('CHE7-3Z-MBRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('CHE7-3Z-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('CHE7-MGRY', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('CHE7-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('CHE7-MTAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG36-MTAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG36-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG48-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LS20-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LS20-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LS20-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL15-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL15-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL15-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL22-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL22-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL22-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL7-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL7-BRN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL7-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSXL13-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSXL13-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSXL13-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL14-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL14-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL14-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL31-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL31-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL31-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('TBAG5-MTAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG5-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG11A-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('TBAG18-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL16-BLK', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL16-BRN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL16-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL32-BRN.1', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL32-TAN.1', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('F953-MNT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('F953-WHT', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('F953-DGRY', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('F953-MRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('F953-DGRN', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('F953-NAV', 'Fashion & Accessories', 'Scarves', null, null, null),
  ('LSL33-GRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL33-RED', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL33-REDBRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL33-BLK', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL33-BRN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL33-TAN', 'Fashion & Accessories', 'Leather', 'Men''s Sling & Crossbody', null, null),
  ('LSL32-BLK', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL32-BRN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null),
  ('LSL32-TAN', 'Fashion & Accessories', 'Leather', 'Handbags', null, null);

update public.website_stock ws
set
  category = t.category,
  subcategory_one = t.subcategory_one,
  subcategory_two = t.subcategory_two,
  subcategory_three = t.subcategory_three,
  subcategory_four = t.subcategory_four,
  updated_at = now()
from move_4_targets t
where ws.sku = t.sku;

update public.archived_products ap
set
  category = t.category,
  subcategory_one = t.subcategory_one,
  subcategory_two = t.subcategory_two,
  subcategory_three = t.subcategory_three,
  subcategory_four = t.subcategory_four,
  updated_at = now()
from move_4_targets t
where ap.sku = t.sku;

commit;