-- 030_orders_client_ref.sql
-- Target project: PORTAL (Proto Trading Website — VITE_SUPABASE_URL).
--
-- Idempotency key for order capture. The storefront generates one client_ref
-- per checkout attempt; both the browser insert and the server-side fallback
-- insert (api/send-order.js) carry it, so a retry can never double-insert the
-- same checkout. Nullable + partial unique index keeps every existing row and
-- code path valid.

alter table public.orders add column if not exists client_ref text;

create unique index if not exists orders_client_ref_key
  on public.orders (client_ref)
  where client_ref is not null;

comment on column public.orders.client_ref is
  'Per-checkout idempotency key (uuid) generated by the storefront. Unique when present; retries of the same checkout reuse it instead of double-inserting.';
