import { writeFile } from 'node:fs/promises';
import { test, expect } from '@playwright/test';
import { installAccessibilityServices, signInCatalogue, catalogueProducts } from './helpers/accessibility-services.js';
test('shopping telemetry joins visits, search and actual product view without blocking shopping', async ({ page, context }) => {
  const events = []; const presence = [];
  await installAccessibilityServices(context);
  await context.route('**/api/shopping-events', async route => { events.push(route.request().postDataJSON()); await route.fulfill({ json: { ok: true } }); });
  await context.route('**/api/presence', async route => { if (route.request().method() === 'POST') presence.push(route.request().postDataJSON()); await route.fulfill({ json: { ok: true } }); });
  await page.clock.install();
  await signInCatalogue(page);
  await expect.poll(() => events.filter(e => e.eventType === 'catalogue_viewed').length).toBe(1);
  await page.clock.fastForward(6000);
  const tip = page.getByRole('region', { name: 'Find more with Proto search' });
  await expect(tip).toBeVisible();
  await tip.getByRole('button', { name: 'Try search' }).click();
  const input = page.getByRole('combobox', { name: 'Search by product name, SKU or barcode' }).filter({ visible: true });
  await expect(input).toBeFocused();
  await input.fill('notebook'); await input.press('Enter');
  await page.clock.runFor(1500);
  await expect.poll(() => events.filter(e => e.eventType === 'search_results_viewed').length).toBe(1);
  const search = events.find(e => e.eventType === 'search_results_viewed');
  expect(search.mainResultsCount).toBeGreaterThan(0); expect(search.instoreResultsCount).toBe(0);
  await page.locator('.product-card').first().getByRole('button', { name: /^View / }).first().click();
  await expect.poll(() => events.filter(e => e.eventType === 'product_viewed').length).toBe(1);
  expect(events.find(e => e.eventType === 'search_result_clicked').searchId).toBe(search.eventId);
  expect(events.find(e => e.eventType === 'product_viewed').searchId).toBe(search.eventId);
  expect(events.some(e => e.eventType === 'search_tip_search_clicked')).toBe(true);
  await expect.poll(() => presence.length).toBeGreaterThan(0);
  expect(new Set(events.map(e => e.sessionId)).size).toBe(1);
  expect(presence[0].sessionId).toBe(search.sessionId);
  expect(new Set(events.map(e => e.eventId)).size).toBe(events.length);
  await page.locator('.pz-modal').getByRole('button', { name: 'Close', exact: true }).click();
  await page.locator('.product-card').first().getByRole('button', { name: /^View / }).first().click();
  await expect.poll(() => events.filter(e => e.eventType === 'product_viewed').length).toBe(2);
  expect(events.filter(e => e.eventType === 'product_viewed')[0].eventId).not.toBe(events.filter(e => e.eventType === 'product_viewed')[1].eventId);
  await page.locator('.pz-modal').getByRole('button', { name: 'Close', exact: true }).click();
  expect(events.filter(e => e.eventType === 'basket_item_added')).toHaveLength(0);
  await page.locator('.product-card').first().getByRole('button', { name: 'Add to Cart', exact: true }).click();
  await expect.poll(() => events.filter(e => e.eventType === 'basket_item_added').length).toBe(1);
  const added = events.find(e => e.eventType === 'basket_item_added');
  expect(added.quantity).toBe(1); expect(added.searchId).toBe(search.eventId);
});

test('Instore search and image telemetry use the Instore source and complete result counts', async ({ page, context }) => {
  const events = [];
  await installAccessibilityServices(context);
  await context.route('**/api/shopping-events', async route => { events.push(route.request().postDataJSON()); await route.fulfill({ json: { ok: true } }); });
  const item = { id: 'CLIP-ON', code: 'CLIP-ON', name: 'Clip on earring', title: 'Clip on earring', isExtendedRange: true, price: 12, image: '/bag_black.png', stockOnHand: 8, stockQty: 8, minQty: 1, categoryPath: [], category: 'Jewellery' };
  await context.route('**/api/extended-range?**', route => route.fulfill({ json: { products: [item], catalogue: [item], total: 1, page: 1, pageSize: 24, tiles: [] } }));
  await signInCatalogue(page);
  await page.goto('/#/instore-products?q=clip+on');
  await expect(page.locator('.instore-grid .product-card').first()).toBeVisible();
  await expect.poll(() => events.filter(e => e.eventType === 'search_results_viewed' && e.source === 'instore').length).toBe(1);
  const search = events.find(e => e.eventType === 'search_results_viewed' && e.source === 'instore');
  expect(search.resultsCount).toBe(1); expect(search.mainResultsCount).toBe(0); expect(search.instoreResultsCount).toBe(1);
  await page.locator('.instore-grid .product-card').first().getByRole('button', { name: /^View / }).first().click();
  await expect.poll(() => events.filter(e => e.eventType === 'product_viewed' && e.source === 'instore').length).toBe(1);
  expect(events.find(e => e.eventType === 'product_viewed' && e.source === 'instore').searchId).toBe(search.eventId);
});

test('a second basket after order submission is tracked without phantom submitted-clear removals', async ({ page, context }) => {
  const events = [];
  await installAccessibilityServices(context, { products: catalogueProducts.map(product => ({ ...product, price: 1500 })) });
  await context.route('**/api/shopping-events', async route => { events.push(route.request().postDataJSON()); await route.fulfill({ json: { ok: true } }); });
  await context.route('**/api/send-order', route => route.fulfill({ json: { success: true, orderId: 'ed130931-a3f5-4207-bd1f-25989291ce03', orderNumber: 'SYNTHETIC-1', emailDeliveryFailed: false } }));
  await signInCatalogue(page);
  await page.goto('/#/?q=notebook');
  await expect.poll(() => events.filter(e => e.eventType === 'search_results_viewed').length).toBe(1);
  await page.locator('.product-card').first().getByRole('button', { name: /^View / }).first().click();
  await expect.poll(() => events.filter(e => e.eventType === 'product_viewed').length).toBe(1);
  await page.locator('.pz-modal').getByRole('button', { name: 'Close', exact: true }).click();
  const add = page.locator('.product-card').first().getByRole('button', { name: 'Add to Cart', exact: true });
  await add.click();
  await expect.poll(() => events.filter(e => e.eventType === 'basket_item_added').length).toBe(1);
  const review = page.getByRole('button', { name: 'Review order request', exact: true });
  if (!(await review.isVisible())) await page.locator('[data-cart-trigger]').filter({ visible: true }).first().click();
  await review.click();
  await expect.poll(() => events.filter(e => e.eventType === 'checkout_started').length).toBe(1);
  const reviewDialog = page.getByRole('dialog', { name: 'Review your order request' });
  await reviewDialog.getByRole('button', { name: 'Close', exact: true }).click();
  await review.click();
  await expect(reviewDialog).toBeVisible();
  expect(events.filter(e => e.eventType === 'checkout_started')).toHaveLength(1);
  await page.getByRole('button', { name: 'Continue to options', exact: true }).click();
  const noUpdates = page.getByRole('button', { name: 'No WhatsApp updates', exact: true });
  if (await noUpdates.isVisible()) await noUpdates.click();
  await page.getByRole('button', { name: 'Continue to delivery', exact: true }).click();
  await page.getByRole('button', { name: /Pick up in store/ }).click();
  await page.getByRole('button', { name: /Send order request.*no payment now/ }).click();
  const confirmation = page.getByRole('dialog', { name: 'Order request received. Thank you.' });
  await expect(confirmation).toBeVisible();
  await expect.poll(() => events.filter(e => e.eventType === 'order_submitted').length).toBe(1);
  expect(events.filter(e => e.eventType === 'basket_item_removed')).toHaveLength(0);
  expect(events.filter(e => e.eventType === 'checkout_started')).toHaveLength(1);
  await confirmation.getByRole('button', { name: 'Close', exact: true }).first().click();
  await add.click();
  await expect.poll(() => events.filter(e => e.eventType === 'basket_item_added').length).toBe(2);
  expect(events.filter(e => e.eventType === 'basket_item_added').map(e => e.quantity)).toEqual([1, 1]);
  expect(events.filter(e => e.eventType === 'basket_item_removed')).toHaveLength(0);
  await writeFile(test.info().outputPath('shopping-events.json'), JSON.stringify(events, null, 2));
});

const analyticsInstoreItem = { id: 'CLIP-ON', code: 'CLIP-ON', name: 'Clip on earring', title: 'Clip on earring', isExtendedRange: true, price: 12, image: '/bag_black.png', stockOnHand: 8, stockQty: 8, minQty: 1, categoryPath: ['Jewellery'], category: 'Jewellery' };
async function instoreEvents(context) {
 const events = [];
 await installAccessibilityServices(context);
 await context.route('**/api/shopping-events', async route => { events.push(route.request().postDataJSON()); await route.fulfill({ json: { ok: true } }); });
 await context.route('**/api/extended-range*', route => route.fulfill({ json: { products: [analyticsInstoreItem], catalogue: [analyticsInstoreItem], total: 1, page: 1, pageSize: 24, tiles: [] } }));
 return events;
}
test('Instore department-first browsing records one visit across root return and refresh', async ({ page, context }) => {
 const events = await instoreEvents(context); await signInCatalogue(page);
 await page.goto('/#/instore-products?browse=Jewellery');
 await expect(page.locator('.instore-grid .product-card').first()).toBeVisible();
 await expect.poll(() => events.filter(e => e.eventType === 'catalogue_viewed' && e.source === 'instore').length).toBe(1);
 await expect.poll(() => events.filter(e => e.eventType === 'department_viewed' && e.source === 'instore').length).toBe(1);
 await page.goto('/#/instore-products'); await expect(page.locator('.instore-grid .product-card').first()).toBeVisible();
 await page.reload(); await expect(page.locator('.instore-grid .product-card').first()).toBeVisible();
 expect(events.filter(e => e.eventType === 'catalogue_viewed' && e.source === 'instore')).toHaveLength(1);
});
test('mixed main search keeps Instore preview and basket linked to the current search only', async ({ page, context }) => {
 const events = await instoreEvents(context); await signInCatalogue(page);
 await page.goto('/#/?q=clip+on');
 await expect.poll(() => events.filter(e => e.eventType === 'search_results_viewed' && e.source === 'main').length).toBe(1);
 const search = events.find(e => e.eventType === 'search_results_viewed' && e.source === 'main');
 await page.locator('.catalog-instore-grid').getByRole('button', { name: 'View Clip on earring', exact: true }).click();
 await expect.poll(() => events.filter(e => e.eventType === 'product_viewed' && e.source === 'instore').length).toBe(1);
 expect(events.find(e => e.eventType === 'product_viewed' && e.source === 'instore').searchId).toBe(search.eventId);
 await page.locator('.pz-modal').getByRole('button', { name: 'Add 1 to order', exact: true }).click();
 await expect.poll(() => events.filter(e => e.eventType === 'basket_item_added' && e.source === 'instore').length).toBe(1);
 expect(events.find(e => e.eventType === 'basket_item_added' && e.source === 'instore').searchId).toBe(search.eventId);
 await page.locator('.pz-modal').getByRole('button', { name: 'Close', exact: true }).click();
 await page.goto('/#/?q=earring');
 await expect.poll(() => events.filter(e => e.eventType === 'search_results_viewed' && e.source === 'main').length).toBe(2);
 const fresh = events.filter(e => e.eventType === 'search_results_viewed' && e.source === 'main').at(-1);
 await page.locator('.catalog-instore-grid').getByRole('button', { name: 'View Clip on earring', exact: true }).click();
 await expect.poll(() => events.filter(e => e.eventType === 'product_viewed' && e.source === 'instore').length).toBe(2);
 expect(events.filter(e => e.eventType === 'product_viewed' && e.source === 'instore').at(-1).searchId).toBe(fresh.eventId);
 expect(fresh.eventId).not.toBe(search.eventId);
});
